"""Single source of truth for bus routing keys."""

MARKET_BARS = "market.bars"
SIGNAL_OPEN = "signals.scenario_open"
SIGNAL_UPDATE = "signals.scenario_update"
SIGNAL_CLOSE = "signals.scenario_close"
ORDER_INTENT = "orders.intent"
ORDER_SUBMITTED = "orders.submitted"
ORDER_FILLED = "orders.filled"
ORDER_REJECTED = "orders.rejected"
RISK_DECISION = "risk.decision"
RISK_CIRCUIT = "risk.circuit"
SENTIMENT_SNAPSHOT = "sentiment.snapshot"
AUDIT_EVENT = "audit.event"
HITL_REQUEST = "hitl.request"
HITL_RESPONSE = "hitl.response"
