FROM python:3.9

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app /app/app
COPY migrations /app/migrations

CMD ["uvicorn", "app.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
