FROM python:3.9

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app /app/app
COPY migrations /app/migrations

CMD ["sh", "-c", "uvicorn app.api.main:app --host $API_HOST --port $API_PORT"]
