FROM python:3.9

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY dashboard /app/dashboard

CMD ["python", "-m", "flask", "run", "--host", "0.0.0.0", "--port", "8080"]
