version: '3.8'

services:
  data_service:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017

  training_service:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://mongo:27017

volumes:
  mongo_data:
version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017

volumes:
  mongo_data:
