"""Description of the changes

Revision ID: 8104afe36029
Revises: e3ed24f70ba0
Create Date: 2024-10-27 04:02:48.004509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8104afe36029'
down_revision = 'e3ed24f70ba0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
