"""Initial migration

Revision ID: e3ed24f70ba0
Revises: 
Create Date: 2024-10-27 04:02:31.997846

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e3ed24f70ba0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('option_chains')
    op.drop_table('open_interests')
    op.drop_table('stock_predictions')
    op.add_column('stocks', sa.Column('predicted_price', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'predicted_price')
    op.create_table('stock_predictions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.VARCHAR(length=14), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('predicted_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='stock_predictions_pkey'),
    sa.UniqueConstraint('version_id', 'symbol', name='unique_prediction')
    )
    op.create_table('open_interests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expiry_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('strike_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('option_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('open_interest', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('change_in_oi', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='open_interests_pkey')
    )
    op.create_table('option_chains',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expiry_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('strike_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('option_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('change', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('volume', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('open_interest', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('implied_volatility', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='option_chains_pkey')
    )
    # ### end Alembic commands ###
